### ISSUE TITLE
Update docs for boot2docker configuration with php 5.6

### ISSUE THREAD

**Issue by hacfi** [docker-php/docker-php#105]
I just noticed that there were some changes to ssl in php 5.6 requiring

the additional ssl settings
```yml
                    CN_match: 'Boot2Docker'
                    verify_peer: false
```
for the context. Will create a PR soon.

**Comment by joelwurtz** [comment]
I'm not a fan of setting verify_peer to false, by default it should check the peer to be sure that the docker server used is trusted, otherwise this library will be vulnerable to man in the middle attack and we, clearly, don't want that.

However there is a problem with the current openssl version on homebrew and certificate from boot2docker, see this issue : https://github.com/boot2docker/boot2docker/issues/808

And php56 of homebrew depends on the openssl of homebrew so you might have this error, my current workaround was to switch to an older version of openssl (1.0.1) and everything work as expected.

**Comment by hacfi** [comment]
@joelwurtz Thanks for the comment - I’ll try to create instructions which will work without disabling `verify_peer`! It took me an hour to make it work at all.

**Comment by joelwurtz** [comment]
I personally have done this : 

```
brew tap homebrew/boneyard
brew versions openssl
```

Choose a version with the corresponding git commit id

```
cd /usr/local/Library
git checkout 86e647b /usr/local/Library/Formula/openssl.rb 
brew reinstall openssl
```

**Comment by joelwurtz** [comment]
Does TLS still failing in MacOsX (don't have a mac anymore) ?

**Comment by joelwurtz** [comment]
Closing this as it seems no longer valid with recent versions of boot2docker, don't hesitate to reopen this if you have this problem.
