### ISSUE TITLE
How to set network

### ISSUE THREAD

**Issue by aarobc** [docker-php/docker-php#175]
I've been digging through the source, attempting to figure out how to set the network for a container. 

This doesn't work:

```
$nwc = new NetworkConfig();                              
$nwc->setNetworks((object)['netw_base']);                                     
$containerManager = $this->docker->getContainerManager();
$containerConfig = new ContainerConfig();                
$containerConfig                                         
    ->setImage('busybox:latest')                         
    ->setEnv(['foo=barr'])                               
    ->setNames(['franklin'])                             
    ->setNetworkSettings($nwc)                           
    ->setCmd(['echo', 'I am running a command']);        
```

It's odd that NetworkConfig's method for setting the network:
 `setNetworks(\ArrayObject $networks = null)`
wants an object rather than just an array. it's unclear to me how to properly set it, and the lack of documentation really doesn't help.

**Comment by joelwurtz** [comment]
This is because of the behavior of json and need to separate array from map. In this library if you see an array then it's a numerical one, no matter what happen.

If you see an \ArrayObject then it indicates that it's a map where key are a string, you can do the following for settings networks in a container : 

```
$networkContainer = new NetworkContainer();
...

$networkConfig->setNetworks(new \ArrayObject([
   'mynetwork' => $networkContainer
]);
```

This diff is mainly to separate empty map `{}` from empty array `[]` which is impossible to do with a simple array.

**Comment by joelwurtz** [comment]
Closing this as this issue is rather old.
