### ISSUE TITLE
Send command to container under specific user

### ISSUE THREAD

**Issue by drsect0r** [docker-php/docker-php#181]
I'm using the ExecManager to send commands to already running containers. How can I specify under what user those commands need to be run?

**Comment by joelwurtz** [comment]
I think this should be a value in the `ExecConfig` when passing it to the create method, but it's not present as i have essentially cc the documentation present here : https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#exec-create and they tell nothing about it :/

If you have time to dig into docker source code to know the name and format of this parameter that would be awesome (then i will udpate the schema to add this). Otherwise it will have to wait a bit more as i don't currently have too much time to handle this.

**Comment by drsect0r** [comment]
@joelwurtz I suspected this. I will try if I can dig up something next week.

**Comment by drsect0r** [comment]
@joelwurtz Is this usefull? 

https://github.com/docker/docker/blob/611d5e4eebc4c6153e49a319360df8de5bdd2e7c/vendor/src/github.com/docker/engine-api/types/configs.go#L44
https://github.com/docker/docker/blob/e5a3f86e447dd659da3c2e759f3c088a0bfcfe3d/daemon/exec.go#L118
https://github.com/docker/docker/blob/641bd7652f0f65712bab60f7a5f8e299dcb5643c/api/client/exec.go#L142

**Comment by joelwurtz** [comment]
Deinitly, i will try to do an update, there is also other bugs open on this library, but i'am in a rush for a project which must go out the 11th, so i may have more time after this date to do all the change (it depends on the bug numbers :) )

**Comment by drsect0r** [comment]
@joelwurtz Any update?

**Comment by joelwurtz** [comment]
Don't have the time to work on docker-php actually, if someone has the time to do a PR about it i will take time to review this.

**Comment by joelwurtz** [comment]
This will be good in 2.0
