### ISSUE TITLE
imageCreate does not throws exception

### ISSUE THREAD

**Issue by Soullivaneuh** [docker-php/docker-php#291]
If the image is not found, the response is returned, nothing thrown.

I have to use `imageCreateLegacy` to have the correct way. BTW, why legacy? It's the method from the fresh new docker-php-api repository. :thinking:

**Comment by SamMousa** [comment]
@Soullivaneuh you are correct.
The issue is with overriding the autogenerated function to support different types of responses (like a stream). 

Regardless the exceptions should still be thrown when passing the option to fetch an object. Note that fetching a response doesn't ever throw an exception.

@joelwurtz is in the process of updating the code generating library to remove the need for overriding the function, for now please explicitly check the return type, the status code, or use the function you mentioned.

**Comment by Soullivaneuh** [comment]
> or use the function you mentioned.

I can't, because I need the image creation wait.

> for now please explicitly check the return type

This is what I do right now, but it's ugly! :trollface:

**Comment by joelwurtz** [comment]
Should be good
